package com.aws.primer.dynamo;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "daily_events")
public class DailyEvents implements Serializable {

	private static final long serialVersionUID = -3534650012619938612L;

	private String eventId;
	private String email;
	private String eventType;
	private String lastEvent;
	private String siteName;

	public DailyEvents(String siteName, String eventType) {
		this.siteName = siteName;
		this.eventType = eventType;
	}
	
	public DailyEvents() {
	}

	@DynamoDBHashKey(attributeName = "eventid")
	@DynamoDBAutoGeneratedKey
	public String getEventId() {
		return eventId;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	@DynamoDBAttribute(attributeName = "email")
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@DynamoDBAttribute(attributeName = "eventtype")
	public String getEventType() {
		return eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

	@DynamoDBAttribute(attributeName = "latestinteraction")
	public String getLastEvent() {
		return lastEvent;
	}

	public void setLastEvent(String lastEvent) {
		this.lastEvent = lastEvent;
	}

	@DynamoDBAttribute(attributeName = "sitename")
	public String getSiteName() {
		return siteName;
	}

	public void setSiteName(String siteName) {
		this.siteName = siteName;
	}

}
