package com.aws.primer.dynamo;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "site_names")
public class SiteNames implements Serializable {

	private static final long serialVersionUID = -3534650012619938613L;

	private String siteId;
	private String siteName;

	public SiteNames() {
	}

	@DynamoDBHashKey(attributeName = "site_id")
	@DynamoDBAutoGeneratedKey
	public String getSiteId() {
		return siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}
	
	public void setSiteName(String siteName) {
		this.siteName = siteName;
	}

	@DynamoDBAttribute(attributeName = "site_name")
	public String getSiteName() {
		return siteName;
	}
}
